INSERT INTO categoria(nome, imagem)
VALUES
    (
      'Vidro',
      'https://raw.githubusercontent.com/IgormBonfim/quasar-media/main/Categorias/VidroCategorias.png'
    ),
    (
      'Farol',
      'https://raw.githubusercontent.com/IgormBonfim/quasar-media/main/Categorias/FarolCategorias.png'
    ),
    (
      'Lanterna',
      'https://raw.githubusercontent.com/IgormBonfim/quasar-media/main/Categorias/LanternaCategorias.png'
    ),
    (
      'Retrovisor',
      'https://raw.githubusercontent.com/IgormBonfim/quasar-media/main/Categorias/RetrovisorCategorias.png'
    ),
    (
      'Para-Choque',
      'https://raw.githubusercontent.com/IgormBonfim/quasar-media/main/Categorias/ParachoqueCategorias.png'
    )
    ;
