INSERT INTO quasarecommerce.cidade (nome_cidade, id_uf) VALUES
-- ES (8)
('Guarapari', 8),
('Itapemirim', 8),
('Viana', 8),
('Vila Velha', 8),
('Vitória', 8),
-- ACRE (1)
('Acrelândia', 1),
('Capixaba', 1),
('Cruzeiro do Sul', 1),
('Porto Acre', 1),
('Rio Branco', 1),
-- ALAGOAS (2)
('Campo Alegre', 2),
('Estrela de Alagoas', 2),
('Feira Grande', 2),
('Maceió', 2),
('Ouro Branco', 2),
-- AMAPÁ (4)
('Amapá', 4), 
('Macapá', 4),
('Porto Grande', 4),
('Pracuúba', 4),
('Vitória do Jari', 4),
-- AMAZONAS (3)
('Alvarães', 3),
('Amaturá', 3),
('Itamarati', 3),
('Itapiranga', 3),
('Manaus', 3),
-- BAHIA (5)
('Porto Seguro', 5),
('Prado', 5),
('Ruy Barbosa', 5),
('Salinas da Margarida', 5),
('Salvador', 5),
-- CEARÁ (6)
('Fortaleza', 6),
('Fortim', 6),
('Frecheirinha', 6),
('General Sampaio', 6),
('Graça', 6),
-- DISTRITO FEDERAL (7)
('Brasília', 7),
('Sudoeste/Octogonal', 7),
('Varjão', 7),
('Park Way', 7),
('SCIA', 7),
-- GOIÁS (9)
('Goiânia', 9),
('Goianira', 9),
('Goiás', 9),
('Goiatuba', 9),
('Gouvelândia', 9),
-- MARANHÃO (10)
('São João do Soter', 10),
('São João dos Patos', 10),
('São José de Ribamar', 10),
('São José dos Basílios', 10),
('São Luís', 10),
-- MATO GROSSO (13)
('Cuiabá', 13),
('Denise', 13),
('Diamantino', 13),
('Dom Aquino', 13),
('Feliz Natal', 13),
-- MATO GROSSO DO SUL (12)
('Campo Grande', 12),
('Caracol', 12),
('Cassilândia', 12),
('Chapadão do Sul', 12),
('Corguinho', 12),
-- MINAS GERAIS (11)
('Belo Horizonte', 11),
('Belo Oriente', 11),
('Belo Vale', 11),
('Berilo', 11),
('Berizal', 11),
-- PARÁ (14)
('Belém', 14),
('Belterra', 14),
('Benevides', 14),
('Bom Jesus do Tocantins', 14),
('Bonito', 14),
-- PARAÍBA (15)
('Itapororoca', 15),
('Itatuba', 15),
('Jacaraú', 15),
('Jericó', 15),
('João Pessoa', 15),
-- PARANÁ (18)
('Cruzeiro do Iguaçu', 18),
('Cruzeiro do Oeste', 18),
('Cruzeiro do Sul', 18),
('Cruzmaltina', 18),
('Curitiba', 18),
-- PERNAMBUCO (16)
('Recife', 16),
('Riacho das Almas', 16),
('Ribeirão', 16),
('Rio Formoso', 16),
('Sairé', 16),
-- PIAUÍ (17)
('Socorro do Piauí', 17),
('Sussuapara', 17),
('Tamboril do Piauí', 17),
('Tanque do Piauí', 17),
('Teresina', 17),
-- RIO DE JANEIRO (19)
('Niterói', 19),
('Rio das Ostras', 19),
('Rio de Janeiro', 19),
('Macaé', 19),
('Campos dos Goytacazes', 19),
-- RIO GRANDE DO NORTE (20)
('Montanhas', 20),
('Monte Alegre', 20),
('Monte das Gameleiras', 20),
('Mossoró', 20),
('Natal', 20),
-- RIO GRANDE DO SUL (23)
('Poço das Antas', 23),
('Pontão', 23),
('Ponte Preta', 23),
('Portão', 23),
('Porto Alegre', 23),
-- RONDÔNIA (21)
('Porto Velho', 21),
('Presidente Médici', 21),
('Primavera de Rondônia', 21),
('Rio Crespo', 21),
('Rolim de Moura', 21),
-- RORAIMA (22)
('Boa Vista', 22),
('Bonfim', 22),
('Cantá', 22),
('Caracaraí', 22),
('Caroebe', 22),
-- SANTA CATARINA (24)
('Ermo', 24),
('Erval Velho', 24),
('Faxinal dos Guedes', 24),
('Flor do Sertão', 24),
('Florianópolis', 24),
-- SÃO PAULO (26)
('São Paulo', 26),
('Guarulhos', 26),
('Ribeirão Preto', 26),
('São Bernardo do Campo', 26),
('Vitória Brasil', 26),
-- SERGIPE (25)
('Aracaju', 25),
('Arauá', 25),
('Areia Branca', 25),
('Barra dos Coqueiros', 25),
('Boquim', 25),
-- TOCANTINS (27)
('Novo Acordo', 27),
('Novo Alegre', 27),
('Novo Jardim', 27),
('Oliveira de Fátima', 27),
('Palmas', 27);


